password = 'pamela.44R3n@t0v1'
gemini_api_key = "AIzaSyBq4gP0D70vb81FKeNqzTiwcSa_9KOudTQ"
[gcp_service_account]
type = "service_account"
project_id = "fiery-booth-296502"
private_key_id = "1e1c21627943024d700cad4643bc17134033a590"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCydFe8laCWttgz
Neb/u/YqxsMJtu9Gyl62eLRT8R0pPQtFLwtCHCjsLnoeAQJtoQ6rYi9RSLj/78RY
wqMu2Q9mqx13XH891/3i82MpVK2Ks0SrAvmpMNfiGAzFLgmdOL8+cs+U9RIqt+C5
9XFdwLZls071LttMeQI3Xf+bWON9jLWsQ+qFd/8DZn50y0VzkctsfnwRJCXorMVU
vDVZLf3dcHyY4TDcemL2pqhXgH7qzQPod+pxbYkFQ1GEVolozI9KC3a6djrHAdMo
JhwNeil4UX5kCNrFhUKrI/caMWQaAMfomxiquEGd5WydBtIKQ6t2wV7LyTmTKec3
7sraJOOzAgMBAAECggEAKWYDCo09nWkae7rX9WDB6UeF7IWDOc1trnAPCWAojy4J
pMmWl4YX2j6n9rjuOsd/szOKXZV80WbqilrQ52fUglFU+yE6pXqre9BRoz9xKPmQ
hwmgKGdb1agVolKdSVtmRlL1JA28YquYlxtA6upvheVUfl2Z40I5SOXmC8BRugic
1mtu0kr1yj9mGNmgEcG5y2FRAu/j09jduj5ZUNdGjKEWdmI/DOX79xzbbvBwD1c+
wveYhuQDnqrxZEEAWVAdFYMVkHNV75+o9hmEHm5C3PpPhBK1x97qjQ266thlIabM
s23WUPg9uNsJqdd6TBm6KUfS01kbH9950VpRcUwdsQKBgQDZ/rfL9XhQPm7qAAbj
dua81JE1eVLr2J6gT6Rfd1qiIXawmsZBGmAQDT4Erav7VQykOW38fujwwmWFa9Hy
1oZix3RHxVnWC4AfWY78BLLpmm7jFv6kN6cjfy+WoQ3+TgSn+khUOJCFuBAJiosZ
l34bt/Dpom9yCbR4YZ4YJQpS0QKBgQDRkOalZAvWp9nDE7U0Vy1XiO44c/y5UnHz
sumwduJuLqIk1wl59sWwVkeAOxQwEjKaQqdMto5rcXTrWkXjqPBihEE0xkTGAfB4
ohIIN67npbFuQrkBOeRg5E2etL2G2XcL2Paf3BVir+4UdwfHTobrPFoZl6RqVEx6
qz2h2bWHQwKBgQCzGcc/1wlmRCU0M5l1QLcJ5Ur4OBmck3igFU7i8FiSZBPzvPWt
f1H1XivaBCYMdC/SrSxkCpCvXcey+oafkQkQFva+ELJiXUiCeT40aFfl/W+lO7sy
iFbVnyUmCGRKzyacK9FJAMAcXMEwVZc7C3Acrd9M1JvjgX24eds90xDMQQKBgQC1
mjPFLyVzJpF2kyV77e/E40xMb3aZwfAtluUbnmopwQ+RjScRId++J4ZegNPFtH9V
Xl1MBQb15KPFL71Qw51MQf+flBEU5alVYFzv8hEHfHZ9biSUA27859q7pTR4Hwsi
oSlW7ok5s+tEoMGE3W/debc6ZkZ8PgDobGxETT0ZsQKBgGJU5XUyMocJ0qTtqZXz
D08crdb8z4bnhL2Kvy+wJHhIJzBgwvZsWN85RsGttCj2cNwxkFMDOu7hBVE+h982
ZkNd2DzzqHb49MjQzwRctym8J71jJ8QxXtffI0TaZS0FlD3U3XjugnIt8VIIdlEc
fVM/CYfuNkNgJJ9GW8GghnXC
-----END PRIVATE KEY-----
"""
client_email = "organizador-financeiro-guepo@fiery-booth-296502.iam.gserviceaccount.com"
client_id = "107526326332210767069"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/organizador-financeiro-guepo%40fiery-booth-296502.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
